server:
  port: 9098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: track-service

  data:
    mongodb:
      repositories:
        enabled: true

      host: localhost
      database: musicDB
      uri:  mongodb://127.0.0.1:27017/musicDB

driverClassName: com.mongodb.jdbc.MongoDriver


logging:
  level:
    com.stackroute: DEBUG